<a href="https://colab.research.google.com/github/ahmad1bakundi-ops/data-engineering-journey/blob/main/lesson_3_finding_insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
DATA_PATH = '/content/drive/MyDrive/data-engineering-journey/lesson-02-data/'
df = pd.read_csv(DATA_PATH + 'nigerian_ecommerce_sales_CLEAN.csv')
df.shape

(724, 11)

In [3]:
df['order_date'] = pd.to_datetime(df['order_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        724 non-null    object
 1   customer_id     724 non-null    int64
 2   customer_name   702 non-null    object
 3   customer_state  707 non-null    object
 4   product         724 non-null    object
 5   category        717 non-null    object
 6   quantity        724 non-null    float64
 7   unit_price_ngn  724 non-null    float64
 8   order_date      713 non-null    datetime64[ns]
 9   payment_method  709 non-null    object
 10  status          724 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 62.3+ KB

In [4]:
df['revenue'] = df['quantity'] * df['unit_price_ngn']
df[['order_id', 'product', 'quantity', 'unit_price_ngn', 'revenue']].head()

    order_id                   product  quantity  unit_price_ngn    revenue
0  ORD-00651          Bottle Garri 5kg       3.0         4110.75   12332.25
1  ORD-00050    Vegetable Oil 5 Litres       1.0        13562.20   13562.20
2  ORD-00102      Tecno Spark 10 Phone       1.0       140450.29  140450.29
3  ORD-00216          Bottle Garri 5kg       4.0         4312.23   17248.92
4  ORD-00566  JAMB Past Questions 2024       1.0         3672.37    3672.37

In [5]:
df.groupby('customer_state')['revenue'].sum()

customer_state
Aba              10002262.75
Abuja             3561500.61
Benin City        4539118.50
Calabar           2454855.13
Enugu             7146522.20
Ibadan            4071759.95
Ilorin            2346786.73
Jos               4771519.36
Kaduna            6532752.69
Kano              2711230.91
Lagos             2794980.35
Onitsha           6415681.98
Owerri            3524683.87
Port Harcourt     6003992.58
Warri             3047521.61
Name: revenue, dtype: float64

In [6]:
df.groupby('customer_state')['revenue'].sum().sort_values(ascending=False)

customer_state
Aba              10002262.75
Enugu             7146522.20
Kaduna            6532752.69
Onitsha           6415681.98
Port Harcourt     6003992.58
Jos               4771519.36
Benin City        4539118.50
Ibadan            4071759.95
Abuja             3561500.61
Owerri            3524683.87
Warri             3047521.61
Lagos             2794980.35
Kano              2711230.91
Calabar           2454855.13
Ilorin            2346786.73
Name: revenue, dtype: float64

In [7]:
df.groupby('category')['order_id'].count().sort_values(ascending=False)

category
Electronics        161
Fashion            141
Groceries          137
Home Appliances     97
Baby Care           72
Books               67
Furniture           42
Name: order_id, dtype: int64

In [8]:
df.groupby('customer_state')['order_id'].count().sort_values(ascending=False)

customer_state
Enugu            66
Owerri           57
Kaduna           54
Aba              48
Jos              48
Ilorin           47
Abuja            47
Ibadan           46
Onitsha          44
Port Harcourt    44
Warri            43
Lagos            42
Calabar          42
Kano             42
Benin City       37
Name: order_id, dtype: int64

In [9]:
df.groupby('customer_state')['revenue'].mean().sort_values(ascending=False)

customer_state
Aba              208380.473958
Onitsha          145810.954091
Port Harcourt    136454.376818
Benin City       122678.878378
Kaduna           120976.901667
Enugu            108280.639394
Jos               99406.653333
Ibadan            88516.520652
Abuja             75776.608723
Warri             70872.595581
Lagos             66547.151190
Kano              64553.116905
Owerri            61836.559123
Calabar           58448.931667
Ilorin            49931.632553
Name: revenue, dtype: float64

In [10]:
df.groupby('customer_state').agg(
    order_count=('order_id', 'count'),
    total_revenue=('revenue', 'sum'),
    avg_order_value=('revenue', 'mean'),
    max_order=('revenue', 'max'),
).sort_values('total_revenue', ascending=False)

                order_count  total_revenue  avg_order_value   max_order
customer_state
Aba                      48    10002262.75    208380.473958  2753618.90
Enugu                    66     7146522.20    108280.639394  1480448.40
Kaduna                   54     6532752.69    120976.901667  1464988.71
Onitsha                  44     6415681.98    145810.954091  2917999.40
Port Harcourt            44     6003992.58    136454.376818  4648841.10
Jos                      48     4771519.36     99406.653333   780918.10
Benin City               37     4539118.50    122678.878378   961742.15
Ibadan                   46     4071759.95     88516.520652   980285.10
Abuja                    47     3561500.61     75776.608723   720061.45
Owerri                   57     3524683.87     61836.559123   626832.30
Warri                    43     3047521.61     70872.595581   628973.10
Lagos                    42     2794980.35     66547.151190   833164.35
Kano                     42     2711230.91     64553.116905   473068.14
Calabar                  42     2454855.13     58448.931667   484482.40
Ilorin                   47     2346786.73     49931.632553   291792.99

In [12]:
df.groupby('category').agg(
    order_count=('order_id', 'count'),
    total_revenue=('revenue', 'sum'),
    avg_order_value=('revenue', 'mean'),
    max_order=('revenue', 'max'),
).sort_values('total_revenue', ascending=False)

                 order_count  total_revenue  avg_order_value   max_order
category
Electronics              161    44330162.99    275342.627267  4648841.10
Home Appliances           97    10779481.62    111128.676495   961742.15
Furniture                 42     7367308.30    175412.102381   745062.00
Fashion                  141     5992878.33     42502.683191   435054.60
Groceries                137     1679298.57     12257.653796   129730.00
Baby Care                 72     1219157.98     16932.749722   124965.30
Books                     67      821111.74     12255.399104    91507.40

In [13]:
df['order_month'] = df['order_date'].dt.to_period('M')
df.groupby('order_month')['revenue'].sum()

order_month
2024-01    4206601.38
2024-02    2504831.74
2024-03    9337800.32
2024-04    5203325.94
2024-05    7848685.15
2024-06    4877739.04
2024-07    4602044.01
2024-08    4025714.10
2024-09    3025180.45
2024-10    9152876.76
2024-11    7087466.57
2024-12    9761806.59
Freq: M, Name: revenue, dtype: float64