<a href="https://colab.research.google.com/github/ahmad1bakundi-ops/data-engineering-journey/blob/main/lesson_2_real_csv_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.listdir('/content/drive/MyDrive/data-engineering-journey/lesson-02-data')

['nigerian_ecommerce_sales.csv']

In [4]:
DATA_PATH = '/content/drive/MyDrive/data-engineering-journey/lesson-02-data/'
df = pd.read_csv(DATA_PATH + 'nigerian_ecommerce_sales.csv')
df

,order_id,customer_id,customer_name,customer_state,product,category,quantity,unit_price_ngn,order_date,payment_method,status
0,ORD-00651,1010,Folake Chukwu,Benin City,Bottle Garri 5kg,Groceries,3,4110.75,09-09-2024,Card,Shipped
1,ORD-00050,1177,Wale Akande,Abuja,Vegetable Oil 5 Litres,Groceries,1,13562.20,2024-09-07,NaN,delivered
2,ORD-00102,1014,Grace Ojo,ibadan,Tecno Spark 10 Phone,Electronics,1,140450.29,"Dec 02, 2024",NaN,Pending
3,ORD-00216,1300,Kemi Olawale,Enugu,Bottle Garri 5kg,Groceries,4,4312.23,10/12/2024,BANK TRANSFER,Cancelled
4,ORD-00566,1221,Gbenga Obi,Kaduna,JAMB Past Questions 2024,Books,1,3672.37,2024-04-02,Transfer,Pending
...,...,...,...,...,...,...,...,...,...,...,...
750,ORD-00505,1120,Emeka Eze,Abuja,Generator 2.5KVA,Home Appliances,1,186914.39,16/11/2024,card,Delivered
751,ORD-00568,1267,Emeka Olawale,Port Harcourt,Bottle Garri 5kg,Groceries,3,4214.00,02/02/2024,POD,Shipped
752,ORD-00293,1273,Bisi Adebayo,Jos,Bottle Garri 5kg,Groceries,3,4448.99,12/10/2024,card,Cancelled
753,ORD-00087,1190,Yemi Chukwu,Lagos,LED Bulb Pack of 5,Home Appliances,1,4631.90,2024-11-27,Pay on Delivery,Shipped
754,ORD-00059,1174,Grace Okafor,Calabar,Sony Wireless Earbuds,Electronics,1,36465.97,2024-11-18,Cash on Delivery,Pending

In [5]:
df.shape

(755, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        755 non-null    object
 1   customer_id     755 non-null    int64
 2   customer_name   733 non-null    object
 3   customer_state  737 non-null    object
 4   product         755 non-null    object
 5   category        748 non-null    object
 6   quantity        755 non-null    object
 7   unit_price_ngn  755 non-null    float64
 8   order_date      744 non-null    object
 9   payment_method  740 non-null    object
 10  status          755 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 65.0+ KB

In [7]:
df.describe()

       customer_id  unit_price_ngn
count   755.000000      755.000000
mean   1151.941722    51467.038954
std      85.589045    98103.827892
min    1000.000000    -1500.000000
25%    1080.000000     6396.960000
50%    1153.000000    13956.170000
75%    1225.000000    40019.305000
max    1300.000000   513814.770000

In [8]:
df.isnull().sum()

order_id           0
customer_id        0
customer_name     22
customer_state    18
product            0
category           7
quantity           0
unit_price_ngn     0
order_date        11
payment_method    15
status             0
dtype: int64

In [9]:
df['customer_state'].value_counts()

customer_state
Enugu            63
Owerri           52
Kaduna           50
Aba              46
Onitsha          43
Jos              42
Ilorin           41
Abuja            41
Calabar          41
Ibadan           40
Kano             39
Benin City       38
Port Harcourt    37
Lagos            37
Warri            34
warri            12
jos               9
ilorin            8
kaduna            7
owerri            6
onitsha           5
port harcourt     5
Enugu State       4
ibadan            4
Ibadan            4
 Kano             3
aba               3
lagos             2
PortHarcourt      2
FCT               2
benin city        2
Lagos State       2
enugu             2
ABUJA             2
 Lagos            2
KANO              1
Portharcourt      1
abuja             1
LAGOS             1
Abuja             1
calabar           1
Benin             1
Name: count, dtype: int64

In [10]:
df['payment_method'].value_counts()

payment_method
Pay on Delivery     99
Cash on Delivery    82
POD                 79
Card                76
card                71
BANK TRANSFER       69
cash                67
Bank Transfer       67
Transfer            67
Wallet              63
Name: count, dtype: int64

In [11]:
df['status'].value_counts()

status
CANCELLED    87
delivered    81
pending      81
returned     80
Cancelled    77
Delivered    76
Pending      71
Returned     70
Shipped      66
SHIPPED      66
Name: count, dtype: int64

In [12]:
df['category'].value_counts()

category
Electronics        170
Fashion            144
Groceries          143
Home Appliances    100
Baby Care           75
Books               71
Furniture           45
Name: count, dtype: int64

In [13]:
df_clean = df.copy()

In [14]:
df_clean['customer_state'] = df_clean['customer_state'].str.strip().str.title()
df_clean['customer_state'].value_counts()

customer_state
Enugu            65
Owerri           58
Kaduna           57
Jos              51
Aba              49
Ilorin           49
Ibadan           48
Onitsha          48
Warri            46
Abuja            45
Kano             43
Calabar          42
Port Harcourt    42
Lagos            42
Benin City       40
Enugu State       4
Portharcourt      3
Fct               2
Lagos State       2
Benin             1
Name: count, dtype: int64

In [15]:
state_corrections = {
    'Lagos State': 'Lagos',
    'Portharcourt': 'Port Harcourt',
    'Fct': 'Abuja',
    'Benincity': 'Benin City',
    'Benin': 'Benin City',
    'Enugu State': 'Enugu',
    'Ph': 'Port Harcourt',
}

df_clean['customer_state'] = df_clean['customer_state'].replace(state_corrections)
df_clean['customer_state'].value_counts()

customer_state
Enugu            69
Owerri           58
Kaduna           57
Jos              51
Ilorin           49
Aba              49
Ibadan           48
Onitsha          48
Abuja            47
Warri            46
Port Harcourt    45
Lagos            44
Kano             43
Calabar          42
Benin City       41
Name: count, dtype: int64

In [16]:
df_clean['payment_method'].value_counts()

payment_method
Pay on Delivery     99
Cash on Delivery    82
POD                 79
Card                76
card                71
BANK TRANSFER       69
cash                67
Bank Transfer       67
Transfer            67
Wallet              63
Name: count, dtype: int64

In [17]:
df_clean['payment_method'] = df_clean['payment_method'].str.strip().str.title()
df_clean['payment_method'].value_counts()

payment_method
Card                147
Bank Transfer       136
Pay On Delivery      99
Cash On Delivery     82
Pod                  79
Transfer             67
Cash                 67
Wallet               63
Name: count, dtype: int64

In [18]:
payment_corrections = {
    'Transfer': 'Bank Transfer',
    'Pod': 'Cash On Delivery',
    'Pay On Delivery': 'Cash On Delivery',
    'Cash': 'Cash On Delivery',  # assuming "Cash" means Cash on Delivery in our e-commerce context
}

df_clean['payment_method'] = df_clean['payment_method'].replace(payment_corrections)
df_clean['payment_method'].value_counts()

payment_method
Cash On Delivery    327
Bank Transfer       203
Card                147
Wallet               63
Name: count, dtype: int64

In [19]:
df_clean['status'] = df_clean['status'].str.strip().str.title()
df_clean['status'].value_counts()

status
Cancelled    164
Delivered    157
Pending      152
Returned     150
Shipped      132
Name: count, dtype: int64

In [20]:
df_clean['quantity'].value_counts()

quantity
1       430
2       158
3        72
4        33
10       26
5        21
-3        4
0         3
5000      3
two       2
TBD       1
999       1
-1        1
Name: count, dtype: int64

In [21]:
df_clean['quantity'] = pd.to_numeric(df_clean['quantity'], errors='coerce')
df_clean['quantity']

0      3.0
1      1.0
2      1.0
3      4.0
4      1.0
      ...
750    1.0
751    3.0
752    3.0
753    1.0
754    1.0
Name: quantity, Length: 755, dtype: float64

In [22]:
df_clean['quantity'].dtype

dtype('float64')

In [23]:
df_clean['quantity'].isnull().sum()

np.int64(3)

In [24]:
df_clean['order_date'] = pd.to_datetime(df_clean['order_date'], format='mixed', dayfirst=True)
df_clean['order_date']

0     2024-09-09
1     2024-09-07
2     2024-12-02
3     2024-12-10
4     2024-04-02
         ...
750   2024-11-16
751   2024-02-02
752   2024-10-12
753   2024-11-27
754   2024-11-18
Name: order_date, Length: 755, dtype: datetime64[ns]

In [25]:
df_clean[['order_id', 'order_date']].head(10)

    order_id order_date
0  ORD-00651 2024-09-09
1  ORD-00050 2024-09-07
2  ORD-00102 2024-12-02
3  ORD-00216 2024-12-10
4  ORD-00566 2024-04-02
5  ORD-00169 2024-12-17
6  ORD-00698 2024-05-02
7  ORD-00277 2024-10-19
8  ORD-00164 2024-01-20
9  ORD-00260 2024-01-29

In [26]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        755 non-null    object
 1   customer_id     755 non-null    int64
 2   customer_name   733 non-null    object
 3   customer_state  737 non-null    object
 4   product         755 non-null    object
 5   category        748 non-null    object
 6   quantity        752 non-null    float64
 7   unit_price_ngn  755 non-null    float64
 8   order_date      744 non-null    datetime64[ns]
 9   payment_method  740 non-null    object
 10  status          755 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 65.0+ KB

In [27]:
# Mark impossible prices as NaN
df_clean.loc[
    (df_clean['unit_price_ngn'] <= 0) | (df_clean['unit_price_ngn'] > 500000),
    'unit_price_ngn'
] = np.nan

# Mark impossible quantities as NaN
df_clean.loc[
    (df_clean['quantity'] < 1) | (df_clean['quantity'] > 50),
    'quantity'
] = np.nan

In [28]:
df_clean[['unit_price_ngn', 'quantity']].describe()

       unit_price_ngn    quantity
count      743.000000  740.000000
mean     48198.099287    1.971622
std      89755.719197    1.834272
min       1157.570000    1.000000
25%       6650.500000    1.000000
50%      13956.170000    1.000000
75%      39291.680000    2.000000
max     497980.710000   10.000000

In [29]:
df_clean[df_clean['unit_price_ngn'] > 200000]

,order_id,customer_id,customer_name,customer_state,product,category,quantity,unit_price_ngn,order_date,payment_method,status
40,ORD-00388,1145,Babatunde Lawal,Onitsha,Samsung Galaxy A15,Electronics,2.0,302626.66,NaT,Cash On Delivery,Returned
89,ORD-00714,1196,NaN,Aba,Samsung Galaxy A15,Electronics,10.0,275361.89,2024-10-16,Wallet,Cancelled
93,ORD-00417,1061,Tochukwu Adesanya,NaN,HP Laptop 15 Inch,Electronics,NaN,458569.77,2024-10-03,Bank Transfer,Returned
128,ORD-00285,1291,Fatima Adeleke,Calabar,HP Laptop 15 Inch,Electronics,1.0,484482.40,2024-07-03,Card,Delivered
139,ORD-00477,1039,Toyin Lawal,Aba,HP Laptop 15 Inch,Electronics,4.0,489386.08,2024-01-06,Cash On Delivery,Returned
230,ORD-00675,1247,Adebayo Adebayo,Kaduna,Samsung Galaxy A15,Electronics,1.0,303905.48,2024-08-19,Cash On Delivery,Returned
242,ORD-00396,1175,Yusuf Nwankwo,Enugu,Samsung Galaxy A15,Electronics,1.0,302003.39,2024-03-15,Card,Cancelled
243,ORD-00458,1022,Toyin Ogundimu,Benin City,Samsung Galaxy A15,Electronics,1.0,299136.98,2024-06-08,Cash On Delivery,Shipped
259,ORD-00125,1163,Yemi Hassan,Owerri,Samsung Galaxy A15,Electronics,1.0,301492.67,2024-12-22,Cash On Delivery,Pending
276,ORD-00358,1214,Zara Ogundimu,Enugu,Samsung Galaxy A15,Electronics,3.0,290439.48,2024-03-01,NaN,Pending
306,ORD-00628,1050,Zara Hassan,Kaduna,HP Laptop 15 Inch,Electronics,1.0,464115.95,2024-04-19,Bank Transfer,Delivered
309,ORD-00644,1276,Musa Abdullahi,Kaduna,Samsung Galaxy A15,Electronics,1.0,287965.36,2024-11-13,Cash On Delivery,Delivered
346,ORD-00183,1047,Wale Adesanya,Lagos,Samsung Galaxy A15,Electronics,3.0,277721.45,2024-10-27,Cash On Delivery,Returned
372,ORD-00069,1096,Tobi Olawale,Enugu,HP Laptop 15 Inch,Electronics,1.0,490271.31,2024-05-27,Cash On Delivery,Cancelled
373,ORD-00143,1300,Grace Bakare,Kaduna,HP Laptop 15 Inch,Electronics,3.0,488329.57,2024-06-04,Cash On Delivery,Delivered
378,ORD-00615,1061,Ronke Abdullahi,Benin City,Samsung Galaxy A15,Electronics,2.0,291387.68,2024-03-18,Card,Pending
383,ORD-00446,1293,Ronke Adeleke,Ilorin,Samsung Galaxy A15,Electronics,1.0,281838.86,2024-07-07,Bank Transfer,Cancelled
391,ORD-00441,1196,Sade Ogundimu,Kaduna,Samsung Galaxy A15,Electronics,2.0,304548.97,2024-10-16,Cash On Delivery,Pending
418,ORD-00263,1103,Ifeanyi Yusuf,Warri,HP Laptop 15 Inch,Electronics,1.0,492604.41,2024-03-13,Bank Transfer,Delivered
420,ORD-00596,1066,Ngozi Okafor,Ibadan,HP Laptop 15 Inch,Electronics,2.0,490142.55,2024-11-04,Bank Transfer,Cancelled
425,ORD-00481,1089,Olumide Hassan,Kano,Samsung Galaxy A15,Electronics,1.0,273877.07,2024-03-15,Cash On Delivery,Cancelled
442,ORD-00248,1157,Yemi Okonkwo,Port Harcourt,HP Laptop 15 Inch,Electronics,10.0,464884.11,2024-05-23,Card,Returned
450,ORD-00178,1008,ADAEZE OKONKWO,Aba,HP Laptop 15 Inch,Electronics,1.0,458760.37,2024-08-12,Bank Transfer,Returned
451,ORD-00525,1133,Tochukwu Adebayo,Ibadan,HP Laptop 15 Inch,Electronics,1.0,473745.44,2024-03-26,Bank Transfer,Shipped
489,ORD-00507,1222,Olumide Yusuf,Warri,Samsung Galaxy A15,Electronics,1.0,272693.52,2024-10-02,Cash On Delivery,Delivered
506,ORD-00381,1128,ronke sani,Abuja,HP Laptop 15 Inch,Electronics,1.0,471867.68,2024-11-18,Cash On Delivery,Delivered
535,ORD-00253,1075,Tunde Hassan,Benin City,HP Laptop 15 Inch,Electronics,2.0,472234.41,2024-03-30,Cash On Delivery,Pending
543,ORD-00557,1060,Ibrahim Onyema,Kaduna,Samsung Galaxy A15,Electronics,1.0,291374.50,2024-06-04,Cash On Delivery,Cancelled
576,ORD-00587,1030,Chinedu Yusuf,Enugu,Samsung Galaxy A15,Electronics,1.0,289443.28,2024-07-14,Cash On Delivery,Delivered
590,ORD-00297,1092,Tunde Adebayo,Kano,HP Laptop 15 Inch,Electronics,1.0,473068.14,2024-03-27,Cash On Delivery,Cancelled
605,ORD-00113,1028,HASSAN ALIYU,NaN,HP Laptop 15 Inch,Electronics,1.0,473913.61,2024-11-26,Cash On Delivery,Shipped
606,ORD-00135,1021,Hassan Ogundimu,Ibadan,HP Laptop 15 Inch,Electronics,1.0,495780.78,2024-07-05,Card,Pending
620,ORD-00165,1018,Maryam Adebayo,Ilorin,Samsung Galaxy A15,Electronics,1.0,291792.99,2024-02-24,Card,Pending
629,ORD-00114,1259,Ibrahim Onyema,Owerri,Samsung Galaxy A15,Electronics,1.0,300753.68,2024-11-29,Bank Transfer,Shipped
634,ORD-00672,1191,Nnamdi Ogundimu,Jos,Samsung Galaxy A15,Electronics,2.0,292510.42,2024-10-01,Cash On Delivery,Delivered
681,ORD-00475,1121,Sade Ojo,Onitsha,Samsung Galaxy A15,Electronics,10.0,291799.94,2024-12-26,Bank Transfer,Shipped
718,ORD-00173,1228,Chinedu Onyema,Kaduna,HP Laptop 15 Inch,Electronics,1.0,497980.71,2024-06-06,Cash On Delivery,Shipped

In [30]:
df_clean.isnull().sum()

order_id           0
customer_id        0
customer_name     22
customer_state    18
product            0
category           7
quantity          15
unit_price_ngn    12
order_date        11
payment_method    15
status             0
dtype: int64

In [31]:
df_clean = df_clean.dropna(subset=['quantity', 'unit_price_ngn'])
df_clean.shape

(729, 11)

In [32]:
df_clean.duplicated().sum()

np.int64(5)

In [33]:
df_clean[df_clean.duplicated(keep=False)]

,order_id,customer_id,customer_name,customer_state,product,category,quantity,unit_price_ngn,order_date,payment_method,status
108,ORD-00096,1251,Babatunde Bello,Benin City,Sony Wireless Earbuds,Electronics,1.0,39184.13,2024-10-26,Cash On Delivery,Shipped
144,ORD-00748,1023,Tobi Nwankwo,Enugu,English Dictionary Oxford,Books,2.0,9670.49,2024-06-29,Bank Transfer,Delivered
160,ORD-00246,1167,Tunde Obi,Benin City,Bottle Garri 5kg,Groceries,2.0,4122.45,2024-07-07,Wallet,Returned
222,ORD-00590,1264,Nnamdi Akande,Benin City,English Dictionary Oxford,Books,2.0,9211.81,2024-12-02,Card,Returned
262,ORD-00170,1188,Sola Abdullahi,Kano,Pressing Iron Steam,Home Appliances,2.0,19031.80,2024-07-31,Bank Transfer,Returned
314,ORD-00246,1167,Tunde Obi,Benin City,Bottle Garri 5kg,Groceries,2.0,4122.45,2024-07-07,Wallet,Returned
526,ORD-00096,1251,Babatunde Bello,Benin City,Sony Wireless Earbuds,Electronics,1.0,39184.13,2024-10-26,Cash On Delivery,Shipped
659,ORD-00170,1188,Sola Abdullahi,Kano,Pressing Iron Steam,Home Appliances,2.0,19031.80,2024-07-31,Bank Transfer,Returned
678,ORD-00590,1264,Nnamdi Akande,Benin City,English Dictionary Oxford,Books,2.0,9211.81,2024-12-02,Card,Returned
740,ORD-00748,1023,Tobi Nwankwo,Enugu,English Dictionary Oxford,Books,2.0,9670.49,2024-06-29,Bank Transfer,Delivered

In [34]:
df_clean = df_clean.drop_duplicates()
df_clean.shape

(724, 11)

In [35]:
df_clean.to_csv(DATA_PATH + 'nigerian_ecommerce_sales_CLEAN.csv', index=False)