<a href="https://colab.research.google.com/github/ahmad1bakundi-ops/data-engineering-journey/blob/main/lesson_with_messy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
messy_data = {
    'customer_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 103, 111, 112, 113, 114],
    'name':        ['Ahmad', 'fatima', ' Bola ', 'Chinedu', 'AISHA', 'Tunde', None, 'Bola', 'Yemi', 'kemi', ' Bola ', 'Ifeanyi', 'Zara', 'Musa', 'Grace'],
    'city':        ['Lagos', 'abuja', 'LAGOS', 'Kano', ' Lagos', 'Abuja', 'Kano', 'lagos', None, 'Abuja', 'LAGOS', 'PortHarcourt', 'port harcourt', 'Kano ', 'abuja'],
    'age':         [28, 34, 250, 45, 29, -5, 38, 45, 31, 27, 250, 40, 33, 150, 36],
    'order_date':  ['2024-01-15', '15/01/2024', 'Jan 16, 2024', '2024-02-01', '2024-02-03', '03/02/2024', '2024-02-10', '2024-02-01', None, '2024-03-01', 'Jan 16, 2024', '2024-03-15', '15/03/2024', '2024-04-01', '2024-04-05'],
    'amount':      ['₦5000', '$50', '5000 NGN', '₦12000', '₦3500', '$120', '₦7500', '₦12000', '₦4000', '₦6000', '5000 NGN', '₦9000', '$80', '₦15000', None],
    'email':       ['ahmad@gmail.com', 'FATIMA@YAHOO.COM', 'bola@gmail.com', 'chinedu@gmailcom', 'aisha@gmail.com', 'tunde@gmail.com', 'unknown@gmail.com', 'bola@gmail.com', 'yemi@gmail.com', 'kemi@gmail.com', 'bola@gmail.com', 'ifeanyi@gmail.com', 'zara@gmail.com', 'musa@gmail.com', 'grace@gmail.com']
}

df = pd.DataFrame(messy_data)
df

,customer_id,name,city,age,order_date,amount,email
0,101,Ahmad,Lagos,28,2024-01-15,₦5000,ahmad@gmail.com
1,102,fatima,abuja,34,15/01/2024,$50,FATIMA@YAHOO.COM
2,103,Bola,LAGOS,250,"Jan 16, 2024",5000 NGN,bola@gmail.com
3,104,Chinedu,Kano,45,2024-02-01,₦12000,chinedu@gmailcom
4,105,AISHA,Lagos,29,2024-02-03,₦3500,aisha@gmail.com
5,106,Tunde,Abuja,-5,03/02/2024,$120,tunde@gmail.com
6,107,None,Kano,38,2024-02-10,₦7500,unknown@gmail.com
7,108,Bola,lagos,45,2024-02-01,₦12000,bola@gmail.com
8,109,Yemi,None,31,None,₦4000,yemi@gmail.com
9,110,kemi,Abuja,27,2024-03-01,₦6000,kemi@gmail.com
10,103,Bola,LAGOS,250,"Jan 16, 2024",5000 NGN,bola@gmail.com
11,111,Ifeanyi,PortHarcourt,40,2024-03-15,₦9000,ifeanyi@gmail.com
12,112,Zara,port harcourt,33,15/03/2024,$80,zara@gmail.com
13,113,Musa,Kano,150,2024-04-01,₦15000,musa@gmail.com
14,114,Grace,abuja,36,2024-04-05,None,grace@gmail.com

In [3]:
df.shape

(15, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  15 non-null     int64
 1   name         14 non-null     object
 2   city         14 non-null     object
 3   age          15 non-null     int64
 4   order_date   14 non-null     object
 5   amount       14 non-null     object
 6   email        15 non-null     object
dtypes: int64(2), object(5)
memory usage: 972.0+ bytes

In [5]:
df['age'].sum()

np.int64(1031)

In [6]:
df.describe()

       customer_id         age
count    15.000000   15.000000
mean    107.200000   68.733333
std       4.195235   80.450044
min     101.000000   -5.000000
25%     103.500000   30.000000
50%     107.000000   36.000000
75%     110.500000   45.000000
max     114.000000  250.000000

In [7]:
df.isnull().sum()

customer_id    0
name           1
city           1
age            0
order_date     1
amount         1
email          0
dtype: int64

In [8]:
df.isnull()

    customer_id   name   city    age  order_date  amount  email
0         False  False  False  False       False   False  False
1         False  False  False  False       False   False  False
2         False  False  False  False       False   False  False
3         False  False  False  False       False   False  False
4         False  False  False  False       False   False  False
5         False  False  False  False       False   False  False
6         False   True  False  False       False   False  False
7         False  False  False  False       False   False  False
8         False  False   True  False        True   False  False
9         False  False  False  False       False   False  False
10        False  False  False  False       False   False  False
11        False  False  False  False       False   False  False
12        False  False  False  False       False   False  False
13        False  False  False  False       False   False  False
14        False  False  False  False       False    True  False

In [9]:
df.isnull().sum()

customer_id    0
name           1
city           1
age            0
order_date     1
amount         1
email          0
dtype: int64

In [10]:
df_clean = df.copy()

In [11]:
df_clean

,customer_id,name,city,age,order_date,amount,email
0,101,Ahmad,Lagos,28,2024-01-15,₦5000,ahmad@gmail.com
1,102,fatima,abuja,34,15/01/2024,$50,FATIMA@YAHOO.COM
2,103,Bola,LAGOS,250,"Jan 16, 2024",5000 NGN,bola@gmail.com
3,104,Chinedu,Kano,45,2024-02-01,₦12000,chinedu@gmailcom
4,105,AISHA,Lagos,29,2024-02-03,₦3500,aisha@gmail.com
5,106,Tunde,Abuja,-5,03/02/2024,$120,tunde@gmail.com
6,107,None,Kano,38,2024-02-10,₦7500,unknown@gmail.com
7,108,Bola,lagos,45,2024-02-01,₦12000,bola@gmail.com
8,109,Yemi,None,31,None,₦4000,yemi@gmail.com
9,110,kemi,Abuja,27,2024-03-01,₦6000,kemi@gmail.com
10,103,Bola,LAGOS,250,"Jan 16, 2024",5000 NGN,bola@gmail.com
11,111,Ifeanyi,PortHarcourt,40,2024-03-15,₦9000,ifeanyi@gmail.com
12,112,Zara,port harcourt,33,15/03/2024,$80,zara@gmail.com
13,113,Musa,Kano,150,2024-04-01,₦15000,musa@gmail.com
14,114,Grace,abuja,36,2024-04-05,None,grace@gmail.com

In [12]:
df_clean['name']

0       Ahmad
1      fatima
2       Bola
3     Chinedu
4       AISHA
5       Tunde
6        None
7        Bola
8        Yemi
9        kemi
10      Bola
11    Ifeanyi
12       Zara
13       Musa
14      Grace
Name: name, dtype: object

In [13]:
df_clean['name'] = df_clean['name'].str.strip()
df_clean['name']

0       Ahmad
1      fatima
2        Bola
3     Chinedu
4       AISHA
5       Tunde
6        None
7        Bola
8        Yemi
9        kemi
10       Bola
11    Ifeanyi
12       Zara
13       Musa
14      Grace
Name: name, dtype: object

In [14]:
df_clean['name'] = df_clean['name'].str.title()
df_clean['name']

0       Ahmad
1      Fatima
2        Bola
3     Chinedu
4       Aisha
5       Tunde
6        None
7        Bola
8        Yemi
9        Kemi
10       Bola
11    Ifeanyi
12       Zara
13       Musa
14      Grace
Name: name, dtype: object

In [15]:
df_clean['name'] = df_clean['name'].str.strip().str.title()

In [16]:
df_clean['city']

0             Lagos
1             abuja
2             LAGOS
3              Kano
4             Lagos
5             Abuja
6              Kano
7             lagos
8              None
9             Abuja
10            LAGOS
11     PortHarcourt
12    port harcourt
13            Kano
14            abuja
Name: city, dtype: object

In [17]:
df_clean['city'] = df_clean['city'].str.strip().str.title()
df_clean['city']

0             Lagos
1             Abuja
2             Lagos
3              Kano
4             Lagos
5             Abuja
6              Kano
7             Lagos
8              None
9             Abuja
10            Lagos
11     Portharcourt
12    Port Harcourt
13             Kano
14            Abuja
Name: city, dtype: object

In [18]:
df_clean['city'] = df_clean['city'].replace('Portharcourt', 'Port Harcourt')
df_clean['city']

0             Lagos
1             Abuja
2             Lagos
3              Kano
4             Lagos
5             Abuja
6              Kano
7             Lagos
8              None
9             Abuja
10            Lagos
11    Port Harcourt
12    Port Harcourt
13             Kano
14            Abuja
Name: city, dtype: object

In [19]:
df_clean['email']

0       ahmad@gmail.com
1      FATIMA@YAHOO.COM
2        bola@gmail.com
3      chinedu@gmailcom
4       aisha@gmail.com
5       tunde@gmail.com
6     unknown@gmail.com
7        bola@gmail.com
8        yemi@gmail.com
9        kemi@gmail.com
10       bola@gmail.com
11    ifeanyi@gmail.com
12       zara@gmail.com
13       musa@gmail.com
14      grace@gmail.com
Name: email, dtype: object

In [20]:
df_clean['email'] = df_clean['email'].str.lower()
df_clean['email']

0       ahmad@gmail.com
1      fatima@yahoo.com
2        bola@gmail.com
3      chinedu@gmailcom
4       aisha@gmail.com
5       tunde@gmail.com
6     unknown@gmail.com
7        bola@gmail.com
8        yemi@gmail.com
9        kemi@gmail.com
10       bola@gmail.com
11    ifeanyi@gmail.com
12       zara@gmail.com
13       musa@gmail.com
14      grace@gmail.com
Name: email, dtype: object

In [21]:
df_clean['email'] = df_clean['email'].replace('chinedu@gmailcom', 'chinedu@gmail.com')
df_clean['email']

0       ahmad@gmail.com
1      fatima@yahoo.com
2        bola@gmail.com
3     chinedu@gmail.com
4       aisha@gmail.com
5       tunde@gmail.com
6     unknown@gmail.com
7        bola@gmail.com
8        yemi@gmail.com
9        kemi@gmail.com
10       bola@gmail.com
11    ifeanyi@gmail.com
12       zara@gmail.com
13       musa@gmail.com
14      grace@gmail.com
Name: email, dtype: object

In [22]:
import numpy as np

In [23]:
df_clean['email'] = df_clean['email'].replace('unknown@gmail.com', np.nan)
df_clean['email']

0       ahmad@gmail.com
1      fatima@yahoo.com
2        bola@gmail.com
3     chinedu@gmail.com
4       aisha@gmail.com
5       tunde@gmail.com
6                   NaN
7        bola@gmail.com
8        yemi@gmail.com
9        kemi@gmail.com
10       bola@gmail.com
11    ifeanyi@gmail.com
12       zara@gmail.com
13       musa@gmail.com
14      grace@gmail.com
Name: email, dtype: object

In [24]:
df_clean.shape

(15, 7)

In [25]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  15 non-null     int64
 1   name         14 non-null     object
 2   city         14 non-null     object
 3   age          15 non-null     int64
 4   order_date   14 non-null     object
 5   amount       14 non-null     object
 6   email        14 non-null     object
dtypes: int64(2), object(5)
memory usage: 972.0+ bytes

In [26]:
df_clean.describe()

       customer_id         age
count    15.000000   15.000000
mean    107.200000   68.733333
std       4.195235   80.450044
min     101.000000   -5.000000
25%     103.500000   30.000000
50%     107.000000   36.000000
75%     110.500000   45.000000
max     114.000000  250.000000

In [27]:
df_clean.isnull().sum()

customer_id    0
name           1
city           1
age            0
order_date     1
amount         1
email          1
dtype: int64

In [28]:
df_clean['order_date']

0       2024-01-15
1       15/01/2024
2     Jan 16, 2024
3       2024-02-01
4       2024-02-03
5       03/02/2024
6       2024-02-10
7       2024-02-01
8             None
9       2024-03-01
10    Jan 16, 2024
11      2024-03-15
12      15/03/2024
13      2024-04-01
14      2024-04-05
Name: order_date, dtype: object

In [29]:
pd.to_datetime(df_clean['order_date'], format='mixed', dayfirst=True)

0    2024-01-15
1    2024-01-15
2    2024-01-16
3    2024-02-01
4    2024-02-03
5    2024-02-03
6    2024-02-10
7    2024-02-01
8           NaT
9    2024-03-01
10   2024-01-16
11   2024-03-15
12   2024-03-15
13   2024-04-01
14   2024-04-05
Name: order_date, dtype: datetime64[ns]

In [30]:
df_clean['order_date'] = pd.to_datetime(df_clean['order_date'], format='mixed', dayfirst=True)

In [31]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  15 non-null     int64
 1   name         14 non-null     object
 2   city         14 non-null     object
 3   age          15 non-null     int64
 4   order_date   14 non-null     datetime64[ns]
 5   amount       14 non-null     object
 6   email        14 non-null     object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 972.0+ bytes

In [32]:
# Sort the entire DataFrame by order date (oldest first)
df_clean.sort_values('order_date')

,customer_id,name,city,age,order_date,amount,email
0,101,Ahmad,Lagos,28,2024-01-15,₦5000,ahmad@gmail.com
1,102,Fatima,Abuja,34,2024-01-15,$50,fatima@yahoo.com
2,103,Bola,Lagos,250,2024-01-16,5000 NGN,bola@gmail.com
10,103,Bola,Lagos,250,2024-01-16,5000 NGN,bola@gmail.com
3,104,Chinedu,Kano,45,2024-02-01,₦12000,chinedu@gmail.com
7,108,Bola,Lagos,45,2024-02-01,₦12000,bola@gmail.com
4,105,Aisha,Lagos,29,2024-02-03,₦3500,aisha@gmail.com
5,106,Tunde,Abuja,-5,2024-02-03,$120,tunde@gmail.com
6,107,None,Kano,38,2024-02-10,₦7500,NaN
9,110,Kemi,Abuja,27,2024-03-01,₦6000,kemi@gmail.com
11,111,Ifeanyi,Port Harcourt,40,2024-03-15,₦9000,ifeanyi@gmail.com
12,112,Zara,Port Harcourt,33,2024-03-15,$80,zara@gmail.com
13,113,Musa,Kano,150,2024-04-01,₦15000,musa@gmail.com
14,114,Grace,Abuja,36,2024-04-05,None,grace@gmail.com
8,109,Yemi,None,31,NaT,₦4000,yemi@gmail.com

In [33]:
# Find the earliest and latest orders
df_clean['order_date'].min(), df_clean['order_date'].max()

(Timestamp('2024-01-15 00:00:00'), Timestamp('2024-04-05 00:00:00'))

In [34]:
# Calculate how many days passed between each customer's order and today
import datetime
(datetime.datetime.now() - df_clean['order_date']).dt.days

0     850.0
1     850.0
2     849.0
3     833.0
4     831.0
5     831.0
6     824.0
7     833.0
8       NaN
9     804.0
10    849.0
11    790.0
12    790.0
13    773.0
14    769.0
Name: order_date, dtype: float64

In [35]:
df_clean['amount']

0        ₦5000
1          $50
2     5000 NGN
3       ₦12000
4        ₦3500
5         $120
6        ₦7500
7       ₦12000
8        ₦4000
9        ₦6000
10    5000 NGN
11       ₦9000
12         $80
13      ₦15000
14        None
Name: amount, dtype: object

In [36]:
df_clean['original_currency'] = np.where(
    df_clean['amount'].str.contains('$', regex=False, na=False),  # condition: contains $
    'USD',                                                          # if True: USD
    'NGN'                                                           # if False: NGN
)
df_clean['original_currency']

0     NGN
1     USD
2     NGN
3     NGN
4     NGN
5     USD
6     NGN
7     NGN
8     NGN
9     NGN
10    NGN
11    NGN
12    USD
13    NGN
14    NGN
Name: original_currency, dtype: object

In [37]:
df_clean.loc[df_clean['amount'].isnull(), 'original_currency'] = np.nan
df_clean['original_currency']

0     NGN
1     USD
2     NGN
3     NGN
4     NGN
5     USD
6     NGN
7     NGN
8     NGN
9     NGN
10    NGN
11    NGN
12    USD
13    NGN
14    NaN
Name: original_currency, dtype: object

In [38]:
df_clean['amount_value'] = df_clean['amount'].str.replace(r'[^\d.]', '', regex=True)
df_clean['amount_value']

0      5000
1        50
2      5000
3     12000
4      3500
5       120
6      7500
7     12000
8      4000
9      6000
10     5000
11     9000
12       80
13    15000
14     None
Name: amount_value, dtype: object

In [39]:
df_clean['amount_value'] = pd.to_numeric(df_clean['amount_value'])
df_clean['amount_value']

0      5000.0
1        50.0
2      5000.0
3     12000.0
4      3500.0
5       120.0
6      7500.0
7     12000.0
8      4000.0
9      6000.0
10     5000.0
11     9000.0
12       80.0
13    15000.0
14        NaN
Name: amount_value, dtype: float64

In [40]:
df_clean['amount_value'].sum()

np.float64(84250.0)

In [41]:
df_clean['amount_naira'] = np.where(
    df_clean['original_currency'] == 'USD',  # condition: is it dollars?
    df_clean['amount_value'] * 1400,          # if True: multiply by exchange rate
    df_clean['amount_value']                  # if False: keep as-is (already naira)
)
df_clean['amount_naira']

0       5000.0
1      70000.0
2       5000.0
3      12000.0
4       3500.0
5     168000.0
6       7500.0
7      12000.0
8       4000.0
9       6000.0
10      5000.0
11      9000.0
12    112000.0
13     15000.0
14         NaN
Name: amount_naira, dtype: float64

In [42]:
df_clean['amount_naira'].sum()

np.float64(434000.0)

In [43]:
df_clean = df_clean.drop(columns='amount')
df_clean

,customer_id,name,city,age,order_date,email,original_currency,amount_value,amount_naira
0,101,Ahmad,Lagos,28,2024-01-15,ahmad@gmail.com,NGN,5000.0,5000.0
1,102,Fatima,Abuja,34,2024-01-15,fatima@yahoo.com,USD,50.0,70000.0
2,103,Bola,Lagos,250,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
3,104,Chinedu,Kano,45,2024-02-01,chinedu@gmail.com,NGN,12000.0,12000.0
4,105,Aisha,Lagos,29,2024-02-03,aisha@gmail.com,NGN,3500.0,3500.0
5,106,Tunde,Abuja,-5,2024-02-03,tunde@gmail.com,USD,120.0,168000.0
6,107,None,Kano,38,2024-02-10,NaN,NGN,7500.0,7500.0
7,108,Bola,Lagos,45,2024-02-01,bola@gmail.com,NGN,12000.0,12000.0
8,109,Yemi,None,31,NaT,yemi@gmail.com,NGN,4000.0,4000.0
9,110,Kemi,Abuja,27,2024-03-01,kemi@gmail.com,NGN,6000.0,6000.0
10,103,Bola,Lagos,250,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
11,111,Ifeanyi,Port Harcourt,40,2024-03-15,ifeanyi@gmail.com,NGN,9000.0,9000.0
12,112,Zara,Port Harcourt,33,2024-03-15,zara@gmail.com,USD,80.0,112000.0
13,113,Musa,Kano,150,2024-04-01,musa@gmail.com,NGN,15000.0,15000.0
14,114,Grace,Abuja,36,2024-04-05,grace@gmail.com,NaN,NaN,NaN

In [44]:
df_clean.shape

(15, 9)

In [45]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        15 non-null     int64
 1   name               14 non-null     object
 2   city               14 non-null     object
 3   age                15 non-null     int64
 4   order_date         14 non-null     datetime64[ns]
 5   email              14 non-null     object
 6   original_currency  14 non-null     object
 7   amount_value       14 non-null     float64
 8   amount_naira       14 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 1.2+ KB

In [46]:
df_clean.describe()

,customer_id,age,order_date,amount_value,amount_naira
count,15.000000,15.000000,14,14.000000,14.000000
mean,107.200000,68.733333,2024-02-14 06:51:25.714285824,6017.857143,31000.000000
min,101.000000,-5.000000,2024-01-15 00:00:00,50.000000,3500.000000
25%,103.500000,30.000000,2024-01-20 00:00:00,3625.000000,5000.000000
50%,107.000000,36.000000,2024-02-03 00:00:00,5000.000000,8250.000000
75%,110.500000,45.000000,2024-03-11 12:00:00,8625.000000,14250.000000
max,114.000000,250.000000,2024-04-05 00:00:00,15000.000000,168000.000000
std,4.195235,80.450044,NaN,4661.782720,50385.819128

In [47]:
df_clean.isnull().sum()

customer_id          0
name                 1
city                 1
age                  0
order_date           1
email                1
original_currency    1
amount_value         1
amount_naira         1
dtype: int64

In [48]:
df_clean

,customer_id,name,city,age,order_date,email,original_currency,amount_value,amount_naira
0,101,Ahmad,Lagos,28,2024-01-15,ahmad@gmail.com,NGN,5000.0,5000.0
1,102,Fatima,Abuja,34,2024-01-15,fatima@yahoo.com,USD,50.0,70000.0
2,103,Bola,Lagos,250,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
3,104,Chinedu,Kano,45,2024-02-01,chinedu@gmail.com,NGN,12000.0,12000.0
4,105,Aisha,Lagos,29,2024-02-03,aisha@gmail.com,NGN,3500.0,3500.0
5,106,Tunde,Abuja,-5,2024-02-03,tunde@gmail.com,USD,120.0,168000.0
6,107,None,Kano,38,2024-02-10,NaN,NGN,7500.0,7500.0
7,108,Bola,Lagos,45,2024-02-01,bola@gmail.com,NGN,12000.0,12000.0
8,109,Yemi,None,31,NaT,yemi@gmail.com,NGN,4000.0,4000.0
9,110,Kemi,Abuja,27,2024-03-01,kemi@gmail.com,NGN,6000.0,6000.0
10,103,Bola,Lagos,250,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
11,111,Ifeanyi,Port Harcourt,40,2024-03-15,ifeanyi@gmail.com,NGN,9000.0,9000.0
12,112,Zara,Port Harcourt,33,2024-03-15,zara@gmail.com,USD,80.0,112000.0
13,113,Musa,Kano,150,2024-04-01,musa@gmail.com,NGN,15000.0,15000.0
14,114,Grace,Abuja,36,2024-04-05,grace@gmail.com,NaN,NaN,NaN

In [49]:
df = pd.DataFrame(messy_data)
df

,customer_id,name,city,age,order_date,amount,email
0,101,Ahmad,Lagos,28,2024-01-15,₦5000,ahmad@gmail.com
1,102,fatima,abuja,34,15/01/2024,$50,FATIMA@YAHOO.COM
2,103,Bola,LAGOS,250,"Jan 16, 2024",5000 NGN,bola@gmail.com
3,104,Chinedu,Kano,45,2024-02-01,₦12000,chinedu@gmailcom
4,105,AISHA,Lagos,29,2024-02-03,₦3500,aisha@gmail.com
5,106,Tunde,Abuja,-5,03/02/2024,$120,tunde@gmail.com
6,107,None,Kano,38,2024-02-10,₦7500,unknown@gmail.com
7,108,Bola,lagos,45,2024-02-01,₦12000,bola@gmail.com
8,109,Yemi,None,31,None,₦4000,yemi@gmail.com
9,110,kemi,Abuja,27,2024-03-01,₦6000,kemi@gmail.com
10,103,Bola,LAGOS,250,"Jan 16, 2024",5000 NGN,bola@gmail.com
11,111,Ifeanyi,PortHarcourt,40,2024-03-15,₦9000,ifeanyi@gmail.com
12,112,Zara,port harcourt,33,15/03/2024,$80,zara@gmail.com
13,113,Musa,Kano,150,2024-04-01,₦15000,musa@gmail.com
14,114,Grace,abuja,36,2024-04-05,None,grace@gmail.com

In [50]:
df_clean['age']

0      28
1      34
2     250
3      45
4      29
5      -5
6      38
7      45
8      31
9      27
10    250
11     40
12     33
13    150
14     36
Name: age, dtype: int64

In [51]:
df_clean.loc[(df_clean['age'] < 18) | (df_clean['age'] > 100), 'age'] = np.nan
df_clean['age']

0     28.0
1     34.0
2      NaN
3     45.0
4     29.0
5      NaN
6     38.0
7     45.0
8     31.0
9     27.0
10     NaN
11    40.0
12    33.0
13     NaN
14    36.0
Name: age, dtype: float64

In [52]:
df_clean.describe()

,customer_id,age,order_date,amount_value,amount_naira
count,15.000000,11.000000,14,14.000000,14.000000
mean,107.200000,35.090909,2024-02-14 06:51:25.714285824,6017.857143,31000.000000
min,101.000000,27.000000,2024-01-15 00:00:00,50.000000,3500.000000
25%,103.500000,30.000000,2024-01-20 00:00:00,3625.000000,5000.000000
50%,107.000000,34.000000,2024-02-03 00:00:00,5000.000000,8250.000000
75%,110.500000,39.000000,2024-03-11 12:00:00,8625.000000,14250.000000
max,114.000000,45.000000,2024-04-05 00:00:00,15000.000000,168000.000000
std,4.195235,6.363247,NaN,4661.782720,50385.819128

In [53]:
df_clean.isnull().sum()

customer_id          0
name                 1
city                 1
age                  4
order_date           1
email                1
original_currency    1
amount_value         1
amount_naira         1
dtype: int64

In [54]:
df_clean = df_clean.dropna(subset=['amount_naira'])
df_clean

,customer_id,name,city,age,order_date,email,original_currency,amount_value,amount_naira
0,101,Ahmad,Lagos,28.0,2024-01-15,ahmad@gmail.com,NGN,5000.0,5000.0
1,102,Fatima,Abuja,34.0,2024-01-15,fatima@yahoo.com,USD,50.0,70000.0
2,103,Bola,Lagos,NaN,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
3,104,Chinedu,Kano,45.0,2024-02-01,chinedu@gmail.com,NGN,12000.0,12000.0
4,105,Aisha,Lagos,29.0,2024-02-03,aisha@gmail.com,NGN,3500.0,3500.0
5,106,Tunde,Abuja,NaN,2024-02-03,tunde@gmail.com,USD,120.0,168000.0
6,107,None,Kano,38.0,2024-02-10,NaN,NGN,7500.0,7500.0
7,108,Bola,Lagos,45.0,2024-02-01,bola@gmail.com,NGN,12000.0,12000.0
8,109,Yemi,None,31.0,NaT,yemi@gmail.com,NGN,4000.0,4000.0
9,110,Kemi,Abuja,27.0,2024-03-01,kemi@gmail.com,NGN,6000.0,6000.0
10,103,Bola,Lagos,NaN,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
11,111,Ifeanyi,Port Harcourt,40.0,2024-03-15,ifeanyi@gmail.com,NGN,9000.0,9000.0
12,112,Zara,Port Harcourt,33.0,2024-03-15,zara@gmail.com,USD,80.0,112000.0
13,113,Musa,Kano,NaN,2024-04-01,musa@gmail.com,NGN,15000.0,15000.0

In [55]:
df_clean.shape

(14, 9)

In [56]:
df_clean[df_clean['customer_id'] == 103]

,customer_id,name,city,age,order_date,email,original_currency,amount_value,amount_naira
2,103,Bola,Lagos,NaN,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
10,103,Bola,Lagos,NaN,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0

In [57]:
df_clean = df_clean.drop_duplicates()
df_clean

,customer_id,name,city,age,order_date,email,original_currency,amount_value,amount_naira
0,101,Ahmad,Lagos,28.0,2024-01-15,ahmad@gmail.com,NGN,5000.0,5000.0
1,102,Fatima,Abuja,34.0,2024-01-15,fatima@yahoo.com,USD,50.0,70000.0
2,103,Bola,Lagos,NaN,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0
3,104,Chinedu,Kano,45.0,2024-02-01,chinedu@gmail.com,NGN,12000.0,12000.0
4,105,Aisha,Lagos,29.0,2024-02-03,aisha@gmail.com,NGN,3500.0,3500.0
5,106,Tunde,Abuja,NaN,2024-02-03,tunde@gmail.com,USD,120.0,168000.0
6,107,None,Kano,38.0,2024-02-10,NaN,NGN,7500.0,7500.0
7,108,Bola,Lagos,45.0,2024-02-01,bola@gmail.com,NGN,12000.0,12000.0
8,109,Yemi,None,31.0,NaT,yemi@gmail.com,NGN,4000.0,4000.0
9,110,Kemi,Abuja,27.0,2024-03-01,kemi@gmail.com,NGN,6000.0,6000.0
11,111,Ifeanyi,Port Harcourt,40.0,2024-03-15,ifeanyi@gmail.com,NGN,9000.0,9000.0
12,112,Zara,Port Harcourt,33.0,2024-03-15,zara@gmail.com,USD,80.0,112000.0
13,113,Musa,Kano,NaN,2024-04-01,musa@gmail.com,NGN,15000.0,15000.0

In [58]:
df_clean.shape

(13, 9)

In [59]:
df_clean[df_clean['customer_id'] == 103]

,customer_id,name,city,age,order_date,email,original_currency,amount_value,amount_naira
2,103,Bola,Lagos,NaN,2024-01-16,bola@gmail.com,NGN,5000.0,5000.0

In [60]:
df_clean.to_csv('cleaned_customer_orders.csv', index=False)