<a href="https://colab.research.google.com/github/ahmad1bakundi-ops/data-engineering-journey/blob/main/ngn_fx_project_01_data_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install yfinance -q

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
PROJECT_PATH = '/content/drive/MyDrive/data-engineering-journey/ngn-fx-project/'

# Create the folder if it doesn't exist
import os
os.makedirs(PROJECT_PATH, exist_ok=True)

PROJECT_PATH

'/content/drive/MyDrive/data-engineering-journey/ngn-fx-project/'

In [4]:
tickers = ['USDNGN=X', 'EURNGN=X', 'GBPNGN=X', 'JPYNGN=X']

data = yf.download(
    tickers,
    start='2015-01-01',
    end='2025-01-01',
    interval='1d',
    progress=False,
    auto_adjust=True
)

data.shape

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['JPYNGN=X']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-01-01 -> 2025-01-01)')

(2607, 21)

In [5]:
data.head()

Price      Adj Close       Close                                         High  \
Ticker      JPYNGN=X    EURNGN=X    GBPNGN=X JPYNGN=X    USDNGN=X    EURNGN=X
Date
2015-01-01       NaN  219.429993  284.239990      NaN  182.300003  219.429993
2015-01-02       NaN  219.429993  286.420013      NaN  181.380005  219.429993
2015-01-05       NaN  218.139999  279.579987      NaN  182.699997  218.139999
2015-01-06       NaN  216.110001  279.869995      NaN  183.199997  216.389999
2015-01-07       NaN  216.389999  278.179993      NaN  183.600006  216.389999

Price                                               Low  ...           \
Ticker        GBPNGN=X JPYNGN=X    USDNGN=X    EURNGN=X  ... JPYNGN=X
Date                                                     ...
2015-01-01  286.359985      NaN  181.380005  219.429993  ...      NaN
2015-01-02  286.950012      NaN  182.899994  218.139999  ...      NaN
2015-01-05  283.130005      NaN  183.399994  216.110001  ...      NaN
2015-01-06  280.299988      NaN  181.949997  216.110001  ...      NaN
2015-01-07  280.040009      NaN  182.279999  214.559998  ...      NaN

Price                         Open                                    Volume  \
Ticker        USDNGN=X    EURNGN=X    GBPNGN=X JPYNGN=X    USDNGN=X EURNGN=X
Date
2015-01-01  181.380005  219.429993  284.239990      NaN  181.380005      0.0
2015-01-02  181.009995  219.429993  286.399994      NaN  181.869995      0.0
2015-01-05  181.500000  218.139999  279.600006      NaN  182.350006      0.0
2015-01-06  180.979996  216.110001  279.869995      NaN  180.979996      0.0
2015-01-07  181.350006  216.389999  278.140015      NaN  182.279999      0.0

Price
Ticker     GBPNGN=X JPYNGN=X USDNGN=X
Date
2015-01-01        0      NaN      0.0
2015-01-02        0      NaN      0.0
2015-01-05        0      NaN      0.0
2015-01-06        0      NaN      0.0
2015-01-07        0      NaN      0.0

[5 rows x 21 columns]

In [6]:
close = data['Close'].copy()
close.head()

Ticker        EURNGN=X    GBPNGN=X  JPYNGN=X    USDNGN=X
Date
2015-01-01  219.429993  284.239990       NaN  182.300003
2015-01-02  219.429993  286.420013       NaN  181.380005
2015-01-05  218.139999  279.579987       NaN  182.699997
2015-01-06  216.110001  279.869995       NaN  183.199997
2015-01-07  216.389999  278.179993       NaN  183.600006

In [17]:
close.columns

Index(['EUR', 'GBP', 'USD'], dtype='object')

In [21]:
close.shape

(2607, 3)

In [22]:
close.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2607 entries, 2015-01-01 to 2024-12-31
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EUR     2604 non-null   float64
 1   GBP     2607 non-null   float64
 2   USD     2606 non-null   float64
dtypes: float64(3)
memory usage: 81.5 KB

In [23]:
close.describe()

               EUR          GBP          USD
count  2604.000000  2607.000000  2606.000000
mean    534.561907   627.444566   481.516527
std     388.161221   456.529020   362.174276
min     206.529999   156.029999     1.000000
25%     355.834999   422.440002   325.750000
50%     423.610001   483.641998   363.299988
75%     481.575005   556.980743   415.390015
max    1864.699951  2232.942871  1696.199951

In [24]:
close.isnull().sum()

EUR    3
GBP    0
USD    1
dtype: int64

In [25]:
close[close['USD'] < 10]

                   EUR         GBP   USD
Date
2015-07-29  216.770004  156.029999  1.00
2016-07-12  309.369995  185.399994  2.80
2017-02-15  331.779999  201.460007  3.14
2017-08-08  427.920013  241.550003  3.62
2018-07-20  416.470001  238.690002  3.59

In [26]:
close[close['GBP'] < 180]

                   EUR         GBP         USD
Date
2015-07-29  216.770004  156.029999    1.000000
2015-12-08  211.539993  163.270004  195.250000
2015-12-30  215.139999  161.559998  196.960007
2016-03-22  221.309998  156.080002   18.000000

In [27]:
close.loc[close['USD'] < 10, 'USD'] = np.nan
close.loc[close['GBP'] < 180, 'GBP'] = np.nan
close.isnull().sum()

EUR    3
GBP    4
USD    6
dtype: int64

In [28]:
close = close.interpolate(method='linear')
close.isnull().sum()

EUR    0
GBP    0
USD    0
dtype: int64

In [30]:
close[close['USD'] < 150]

                   EUR         GBP   USD
Date
2016-03-22  221.309998  285.740005  18.0
2016-06-28  308.399994  205.740005  28.0
2016-12-02  331.690002  220.940002  33.0

In [34]:
close[close['GBP'] < 250]

                   EUR         GBP         USD
Date
2016-06-28  308.399994  205.740005  278.925003
2016-07-12  309.369995  185.399994  280.490005
2016-08-03  352.070007  215.039993  313.820007
2016-12-02  331.690002  220.940002  314.000000
2017-02-15  331.779999  201.460007  314.000000
2017-08-08  427.920013  241.550003  361.000000
2018-07-20  416.470001  238.690002  360.500000

In [35]:
# GBP should always be greater than USD historically
# Any row where GBP <= USD is a data error
bad_gbp_mask = close['GBP'] <= close['USD']
close.loc[bad_gbp_mask, 'GBP'] = np.nan
close.isnull().sum()

EUR    0
GBP    9
USD    0
dtype: int64

In [36]:
close = close.interpolate(method='linear')
close.isnull().sum()

EUR    0
GBP    0
USD    0
dtype: int64

In [37]:
close.describe()

               EUR          GBP          USD
count  2607.000000  2607.000000  2607.000000
mean    534.403472   628.678642   482.317704
std     387.965825   456.703779   361.348080
min     206.529999   269.850006   178.610001
25%     356.039993   425.921844   337.035004
50%     423.559998   483.679993   363.269989
75%     481.570007   556.980743   415.390015
max    1864.699951  2232.942871  1696.199951

In [38]:
close[close['GBP'] <= close['USD']]

Empty DataFrame
Columns: [EUR, GBP, USD]
Index: []

In [39]:
close.to_csv(PROJECT_PATH + 'ngn_fx_daily_clean.csv')